---
apiVersion: v1
kind: Service
metadata:
  name: go-web-app-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: go-web-app
  ports:
    - port: 80
      targetPort: 8080
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodeport }}
      {{- end }}